#---------------------------
# Hexo Theme Fluid
#---------------------------

favicon: /img/saturn.ico
apple_touch_icon: /img/saturn.ico

code:
  copy_btn: true
  language:
    enable: true
    default: "TEXT"
  highlight:
    enable: true
    lib: "highlightjs"
    highlightjs:
      style: "github gist"
      style_dark: "dark"

fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false
  
  progressbar:
    enable: true
    height_px: 3
    color: "#00f2ff"

dark_mode:
  enable: true
  default: dark

navbar:
  blog_title: "IDV.NG | Neon City 霓虹都市"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

index:
  banner_img: /img/saturn.png
  banner_img_height: 100
  slogan:
    enable: true
    text: "系统已唤醒，数据传输中..."

post:
  banner_img: https://images.unsplash.com/photo-1614728263952-84ea256f9679
  meta:
    date: { enable: true, format: "LL a" }
    wordcount: { enable: true }
    min2read: { enable: true }
  toc:
    enable: true
    placement: right
    collapseDepth: 0

footer:
  content: 'Copyright 2026 © <a href="https://idv.ng" target="_blank"><span>IDV.NG 数字群岛</span></a> . All Rights Reserved'

lazyload:
  enable: true
  loading_img: /img/loading.gif
