# 站点基础信息
title: Neon City 霓虹都市
subtitle: 赛博朋克文化，科幻小说，
description: "Navigating the neon currents to a promised shore. 这里是数字群岛的深空分区，记录穿越霓虹湍流的航行日志。"
keywords: "赛博朋克,科幻小说,Cyberpunk,IDV.NG,Neon City"
author: CyMIR
language: zh-CN
timezone: Asia/Shanghai

# URL 设置
url: https://cyber.idv.ng
root: /

# 目录与主题（关键！）
source_dir: source
public_dir: public
theme: fluid

# 部署设置
deploy:
  type: git
