# 站点基础信息
title: IDV.NG | PROJECT NEON
subtitle: 赛博朋克叙事
author: CyMIR
language: zh-CN
timezone: Asia/Shanghai

# URL 设置
url: https://cyber.idv.ng
root: /

# 目录与主题（关键！）
source_dir: source
public_dir: public
theme: fluid

# 部署设置
deploy:
  type: git
